name: Will Fallows Portfolio

description: This is a sample Jekyll Blog.

# Your name, as you want it to appear underneath each post and in the footer
author: Will Fallows

# Your email if you want it to be linked on the contact page
author_email: will@willfallows.com

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://willfallows.com/

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
markdown: rdiscount

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# How many articles do you wish to appear on the front page:
paginate: 3

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]